#include"bass.h"
#include"bass_fx.h"
#include"basscb.h"
#include"record.h"
#include"tags.h"
#include"string_manip.h"
#include"tooltips.h"
#include"seekslider.h"
#include"btn_record.h"
#include"btn_play.h"
#include"btn_pause.h"
#include"btn_stop.h"
#include"volslider.h"
#include"Time.h"
#include"mainform.h"


#include"context.h"
#include"menufx.h"
#include"registry.h"

#include"comvis.h"
#include"oval.h"
#include"top.h"
